# Generated by Django 6.0.4 on 2026-04-08 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField(help_text='Age in years')),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], help_text='1=Male, 2=Female')),
                ('height', models.FloatField(help_text='Height in cm')),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('smoke', models.BooleanField(default=False, help_text='Smoker?')),
                ('alco', models.BooleanField(default=False, help_text='Alcohol consumer?')),
                ('active', models.BooleanField(default=True, help_text='Physically active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of measurement')),
                ('ap_hi', models.FloatField(help_text='Systolic blood pressure (mmHg)')),
                ('ap_lo', models.FloatField(help_text='Diastolic blood pressure (mmHg)')),
                ('cholesterol', models.IntegerField(choices=[(1, 'Normal'), (2, 'Above Normal'), (3, 'Well Above Normal')], default=1, help_text='Cholesterol level: 1=Normal, 2=Above Normal, 3=Well Above Normal')),
                ('gluc', models.IntegerField(choices=[(1, 'Normal'), (2, 'Above Normal'), (3, 'Well Above Normal')], default=1, help_text='Glucose level: 1=Normal, 2=Above Normal, 3=Well Above Normal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='api.patient')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.IntegerField(help_text='0=Low Risk, 1=High Risk')),
                ('probability', models.FloatField(help_text='Probability of high risk (0–1)')),
                ('data_type_used', models.CharField(choices=[('real', 'Real'), ('hybrid', 'Hybrid')], default='real', help_text='Whether real or hybrid (synthetic) data was used', max_length=10)),
                ('shap_values', models.JSONField(blank=True, help_text='SHAP feature attributions dict or null', null=True)),
                ('shap_warning', models.TextField(blank=True, default='', help_text='Warning message if SHAP could not be computed')),
                ('records_used', models.IntegerField(default=0, help_text='Number of records used (after normalization)')),
                ('records_provided', models.IntegerField(default=0, help_text='Number of records originally provided')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='api.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
