# Generated by Django 6.0.4 on 2026-04-12 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiabetesRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(help_text="Date of measurement")),
                ("pregnancies", models.IntegerField(default=0, help_text="Number of pregnancies")),
                ("glucose", models.FloatField(help_text="Glucose level (mg/dL)")),
                ("blood_pressure", models.FloatField(help_text="Blood pressure (mmHg)")),
                ("skin_thickness", models.FloatField(help_text="Skin thickness (mm)")),
                ("insulin", models.FloatField(help_text="Insulin level")),
                ("bmi", models.FloatField(help_text="Body Mass Index")),
                ("diabetes_pedigree_function", models.FloatField(help_text="Diabetes pedigree function")),
                ("age", models.IntegerField(help_text="Age in years")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="diabetes_records", to="api.patient")),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="DiabetesPrediction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("prediction", models.IntegerField(help_text="0=Low Risk, 1=High Risk")),
                ("probability", models.FloatField(help_text="Probability of high risk (0-1)")),
                ("shap_values", models.JSONField(blank=True, help_text="SHAP feature attributions dict or null", null=True)),
                ("shap_warning", models.TextField(blank=True, default="", help_text="Warning message if SHAP could not be computed")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="diabetes_predictions", to="api.patient")),
                ("record", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="predictions", to="api.diabetesrecord")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
