# Generated by Django 6.0.4 on 2026-04-08 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.IntegerField(choices=[(0, 'Female'), (1, 'Male')])),
                ('height', models.FloatField(help_text='Height in centimetres')),
                ('weight', models.FloatField(help_text='Weight in kilograms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_on', models.DateField(help_text='Date of clinical measurement')),
                ('age', models.IntegerField(help_text='Patient age at time of measurement (years)')),
                ('ap_hi', models.IntegerField(help_text='Systolic blood pressure (mmHg)')),
                ('ap_lo', models.IntegerField(help_text='Diastolic blood pressure (mmHg)')),
                ('cholesterol', models.IntegerField(choices=[(1, 'Normal'), (2, 'Above normal'), (3, 'Well above normal')], default=1)),
                ('gluc', models.IntegerField(choices=[(1, 'Normal'), (2, 'Above normal'), (3, 'Well above normal')], default=1)),
                ('smoke', models.BooleanField(default=False)),
                ('alco', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='api.patient')),
            ],
            options={
                'ordering': ['recorded_on'],
            },
        ),
    ]
